program: train_git_base_multimodal.py
name: baseline
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  lr:
    values: [5e-5]
  batch_size:
    values: [32]
  n_epochs:
    values: [10]
  min_save_every:
    values: [200]
  n_workers:
    values: [28]
  optimizer:
    values: ["adamw"]
  dataset_size:
    values: [-1]
  seed:
    values: [0, 1, 2, 3, 4]
  do_curriculum:
    values: [False]  # This is False for standard-finetuning.
  model_type:
    values: ['causal_lm']  # Can be 'causal_lm' or 'sequence'.
  max_token_length:
    values: [50]