program: src/train_git_base_multimodal.py
name: cl_multimodal_train_val_text_init
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  lr:
    values: [1e-5]
  batch_size:
    values: [32]
  n_epochs:
    values: [8]
  min_save_every:
    values: [1]
  n_workers:
    values: [6]
  optimizer:
    values: ["adam"]
  do_curriculum:
    values: [True]  # This is True for CL.
  dataset_size:
    values: [-1]
  seed:
    values: [0]
  model_name:
    values: ['flamingo', 'git']
  model_type:
    values: ['causal_lm']  # Can be 'causal_lm' or 'sequence'.
  max_token_length:
    values: [50]
  initialize_with_text:
    values: [True]
  use_accelerate:
    values: [False]
  fp16:
    values: [True]
  load_optimizer:
    values: [False]
  train_on_full_data:
    values: [True]
  do_val:
    values: [True]
  wandb_mode:
    values: ['online']